// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrdEhW9XvI4w-t-_kM-JCNmJkKgJnqNYE',
    appId: '1:10451994269:web:eeade7b91067c734c8b674',
    messagingSenderId: '10451994269',
    projectId: 'euclaim-95176',
    authDomain: 'euclaim-95176.firebaseapp.com',
    storageBucket: 'euclaim-95176.firebasestorage.app',
    measurementId: 'G-6G48WVV2LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmCKL0HzX5E-ecREJP4vszkjCUOuNdwLY',
    appId: '1:10451994269:android:e9899a56b3dc9012c8b674',
    messagingSenderId: '10451994269',
    projectId: 'euclaim-95176',
    storageBucket: 'euclaim-95176.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmZYpE8AvHrrdezFgc9GXqPQOtJc_OA0Q',
    appId: '1:10451994269:ios:4ea9ee705124444bc8b674',
    messagingSenderId: '10451994269',
    projectId: 'euclaim-95176',
    storageBucket: 'euclaim-95176.firebasestorage.app',
    iosBundleId: 'com.euclaim.mobile',
  );
}
